### ISSUE TITLE
Wind speed and rain maps not working

### ISSUE THREAD

**Issue by SiBell** [birminghamurbanobservatory/public-data-hub#1]
Unlike air temp and relative humidity these two aren't plotting

**Comment by Gramcito** [comment]
Are you referring to the map or graph? If map, none of the buttons are working to display observations at the moment... I think you broke that! :-p

**Comment by SiBell** [comment]
The map. Ah yes so they are. It's to do with the location. It can't find it at the moment. It'll be something do with `location` or `centroid` property or that fact we haven't add a `forMap` object, which I think you did before. Let me know if you want me to investigate this.

**Comment by SiBell** [comment]
Ok, this is because I've started ingesting observations that don't have a location yet. I think the best way to handle this is on the server side. I'll have a go now adding adding the following query parameter

`.../observations?location__exists=true`

**Comment by SiBell** [comment]
Fixed now with the addition of a `location__exists` query parameter to the API. I've updated the angular code accordingly.
