### ISSUE TITLE
Platform side bar and observation modal should appear straight away

### ISSUE THREAD

**Issue by SiBell** [birminghamurbanobservatory/public-data-hub#119]
It would be better to have these appear straight away when a map marker is clicked, and show spinners inside them while the data loads.

**Comment by Gramcito** [comment]
I never have spare time, btw! 

My first suggestion though is to load the sidebar and modal independently of the data and ideally with skeleton text rather than spinners. I'll try and have a crack at it this week.

**Comment by SiBell** [comment]
Sounds good to me, cheers.

**Comment by Gramcito** [comment]
Okay, the state of play: made a new branch (instant-modals) which also has fixes for Issue 126 on. Have skeleton text working fine with loading delay. 
However, the issue with the slide-out not appearing straight away appears to be more related to the map redraw to re-centre on the clicked pin.

**Comment by Gramcito** [comment]
Definitely a map redraw issue. Try commenting our Line 81 of the google-map.service.ts.

**Comment by SiBell** [comment]
Ok yup, I see, good work. Having played around whilst that line was commented it doesn't actually bother me too much not having it recenter on a clicked marker. So let's get rid of that feature. The skeleton text works really nicely with the sidebar. Can you add something similar for the modal?

Also you've probably noticed I did a big directory/file restructure as I think we were following two different conventions and thus had more directories than we needed. Hopefully you agree it's a little tidier now. Also it's all 2-space indents now, sorry 😈

**Comment by Gramcito** [comment]
Have been hunting for a solution, I think the only way would have been to use web workers and that's tricky as they do not have access to the DOM and data is copied not referenced when passed in. 

Re: directory structure and indenting: I care exactly this much: 0.0000000R.  
:-)

**Comment by Gramcito** [comment]
You can merge branch 'instant-modals' at your convenience. No breaking changes through you do need to do an npm update/install as I bumped Tailwind to 1.7. 

Merging 'instant-modals' will also allow you to close #126 and #127.
