### ISSUE TITLE
Deployment legend below map

### ISSUE THREAD

**Issue by SiBell** [birminghamurbanobservatory/public-data-hub#15]
As discussed, create a colour-coded legend below the map with the _deployment_ names, so the user can tell what _deployment_ the different coloured map markers belong to.

We can also use this legend to filtered out certain deployments. For example:

1. A user clicks a deployment name in the legend.
2. All other deployment names in the legend are greyed out.
3. Only platforms from the selected deployment are shown on the map.
4(a). If the user clicks on the same deployment name again then everything is made visible again.
4 (b). If the user clicks on one of the greyed out deployment names then only platforms from this new deployment are shown on the map.

**Comment by Gramcito** [comment]
I went with a checkbox to show which deployment selected as 1. more typically of a filter, 2. changing the appearance of something not selected is a little messy when you have also have the 'nothing selected' option as well. if you follow. 

Anyway, let me know. 

Needs a code tidy up and some comments as was just getting something working... went with a form array option initially but that didn't work out. :-/

**Comment by SiBell** [comment]
Looks great to me. Feel free to close this issue once you've had a tidy up.
