### ISSUE TITLE
Ability to link to specific observation

### ISSUE THREAD

**Issue by SiBell** [birminghamurbanobservatory/public-data-hub#18]
It will be handy to have a URL that has the observation ID included, e.g:

`https://data.birminghamurbanobservatory/observations/abc123`

External websites can then link to a specific observation. This observation component can have all the same information and links in it as the observation modal, it's just on a standalone page rather than in a modal.

This ties in with us modifying the buttons on modal, e.g. dropping `Explore` in favour of `Plot full timeseries` or `See map of similar observations`

**Comment by Gramcito** [comment]
Can be reached from the modal, url is /observation/:id, and is lazy loaded. 

Take a look at let me know anything you want adding.

**Comment by SiBell** [comment]
Good work. I'm just about to push some code that has tidied this page up a little bit. I've also created issue #40 as a possible addition.
