### ISSUE TITLE
Edit URL approach on graph page

### ISSUE THREAD

**Issue by SiBell** [birminghamurbanobservatory/public-data-hub#29]
I'm thinking it might be worth pulling out the platform ID and observable property ID from the URL path on the /observe page and have them as query string parameters instead. This is partly because the platform ID isn't necessarily essential.

We'll also probably want to add the `unit` as a query parameter too, as we only ever want to be plotting one unit at once, e.g. `degree-celsius` or `kelvin`.

If the user tries to visit the page with any of these essential query parameters missing then load a modal that forces them to select what they want to plot. 

I'd say the essential parameters are:

- observed property
- unit
- start
- end

Then optional extras would be things like:

- the platform id
- deployment id
- discipline
- aggregation
- feature of interest
- procedure

These are all timeseries properties, and should be mapped straight to the query parameters of the getTimeseries request.

We may also want to filter out observations that have been flagged, this is a parameter (`flags__exists`) that is applies to the request for observations.

**Comment by Gramcito** [comment]
The timeseries api call is using the platform id though, to get all timeseries. Is that not actually necessary?

**Comment by SiBell** [comment]
As discussed on Skype, happy to leave the platform ID as a path segment, but we will need to add the Unit as a required query parameter.

**Comment by SiBell** [comment]
Implemented. Sorry @Gramcito the platform ID is no longer a path segment. I've favoured code simplification over pretty URLs.
