### ISSUE TITLE
Show the aggregation and duration in the sidebar and modal

### ISSUE THREAD

**Issue by SiBell** [birminghamurbanobservatory/public-data-hub#3]
Observations now have an `aggregation` property (e.g. `Instant`, `Average`, `Maximum`) and a `duration`.

In sidebar, if the aggregation is not `Instant` then add some small text, e.g. below the value, saying 'Maximum over 5 minutes'.

It's also worth showing this aggregation type and duration in the observation modal, as well the `hasBeginning` and `hasEnd` properties.

**Comment by SiBell** [comment]
I've added the various aggregations that may exist to the database and thus they can be accessed here:

https://api.birminghamurbanobservatory.com/aggregations

Or for a single one: 

https://api.birminghamurbanobservatory.com/aggregations/Maximum

**Comment by Gramcito** [comment]
Pushed up some code that addresses this, let me know what you think.

**Comment by SiBell** [comment]
Great work. I've made some very minor adjustments (253665e777480d36619c1e9355aa14382e1b3b9d) but it was exactly what i was after.
