### ISSUE TITLE
Error on grass temp graph page

### ISSUE THREAD

**Issue by SiBell** [birminghamurbanobservatory/public-data-hub#31]
Currently nothing is plotting [here](https://data.birminghamurbanobservatory.com/observe/elms-cottage-meteorological-enclosure/grass-surface-temperature?start=2020-06-03T20:17:30.017Z&end=2020-06-04T20:17:30.018Z).

The error in the console is: `Cannot read property 'observedProperty' of undefined` within the `drawChart` function.

**Comment by Gramcito** [comment]
Fixed, basically because there was no data for the default window. We might want to think about what to do in that case.
