### ISSUE TITLE
Implement a bar graph capable of showing precipitation depth

### ISSUE THREAD

**Issue by SiBell** [birminghamurbanobservatory/public-data-hub#36]
The example in this [stackoverflow](https://stackoverflow.com/questions/32138505/chart-js-dynamic-bar-width) post is what I'm after. Hopefully the solution proposed helps...

The following [link](http://localhost:4200/observe/allens-croft-primary-school/precipitation-depth?start=2020-06-05T06:15:47.894Z&end=2020-06-05T12:15:47.894Z) should show such a chart because the platform `allens-croft-primary-school` hosted a rain gauge. For some reason it is throwing an error at the moment though.

**Comment by Gramcito** [comment]
I cannot see a way to show variable width columns with CanvasJS at all, and it doesn't look like any of the main packages allow that - ChartJS with that hack only. 

Thoughts?

**Comment by SiBell** [comment]
I need to have a deeper delve into this at some point, but just quickly I did spot [this](https://canvasjs.com/javascript-charts/multi-series-step-line-chart/) type of chart which might get us most of the way there. I had also been thinking that it could work for showin max and min values too. The main issue I see with it though is that the marker placement is a little confusing, although we might be able to hide the marker. Almost want a brainchild of this step chart with an [area](https://canvasjs.com/html5-javascript-area-chart/) chart.

**Comment by SiBell** [comment]
Turns out such a brainchild exists: https://canvasjs.com/javascript-charts/step-area-chart/

**Comment by SiBell** [comment]
Might need to do a little bit of post-processing of the data before we plot it though, for example if the hasEnd is not the same as the hasBeginning of the next observation we may need to insert a [null](https://canvasjs.com/javascript-charts/multi-series-step-line-chart/) value to make it clear on the chart that data is missing.

Another option is that we simply don't plot `precipitation-depth` on a chart, instead we just sum up the totals over the last hour, day, week and show those instead (being careful to watch for missing data). This ties in with issue #43 which highlights that the average user might find such graphs overcomplicated.

If the user needs to see exactly when rainfall intensity was highest then there's still `precipitation-rate` which is much better suited to plotting on a bog-standard line graph.

**Comment by SiBell** [comment]
Sticking with the standard column chart, but displaying the duration (e.g. over 10 minutes) in the tooltip might be enough.

It's proving very difficult to have columns with variable widths. It's not impossible, but I don't actually think it will look any nicer.

**Comment by SiBell** [comment]
When it hasn't rained all day the graph is bare, we could do with someway of conveying the difference between no rain and no data.

**Comment by SiBell** [comment]
Closing as the current column chart implementation is actually good enough now that the duration has been added to the tooltip.
