### ISSUE TITLE
Google Maps API Key

### ISSUE THREAD

**Issue by SiBell** [birminghamurbanobservatory/public-data-hub#37]
@Gramcito where's the Google Maps API Key come from that's used in the file *google-map.service.ts*? 

Want me to change it to one owned by the BirminghamUrbanObservatory google account?

**Comment by Gramcito** [comment]
It is from my google api account - backed by my personal finance... so if you can and wish to change it please do so.

**Comment by SiBell** [comment]
This has now been changed to development and production keys registered to the Bham Urban Obs Google Account.
