### ISSUE TITLE
Make use of the observation modal on the graph/chart page

### ISSUE THREAD

**Issue by SiBell** [birminghamurbanobservatory/public-data-hub#39]
Another shower thought: can we make use of the observation modal on the `/observe` page, e.g. when a user clicks on a point on line on the graph the observation modal pops up.

Of course this relies on chart.js supporting click events for line markers, and somehow working out what the observation ID is of that point.

Couple of reasons for doing this:

- We could then omit most of the information currently in the coloured timeseries components. All these would need to show is the difference between the components.
- When we plot maximum, minimum and average values on the line graph it would be good to have a mechanism to show the user what period that average/max/min is over. This is something the observation modal can do.
- Eventually we might need to show textual rather than numerical data. In which case we might use a table rather than a line graph. Either way we can still make use of the observation modal, e.g. when a user clicks on a row on the table.

We can still keep the current hover feature to quickly show the value and timestamp of a marker. We should also make use of the "Page Title" to tell the user what's being plotted. E.g. "Soil Temperature observations from Elm's Cottage meteorological enclosure"

**Comment by Gramcito** [comment]
Yes, there is a click event on the point I believe. As the modal is already isolated behind a service it should be pretty easy to link up provided I can get the observation ID to the click event.

**Comment by SiBell** [comment]
Implemented
