### ISSUE TITLE
Colouring platform map markers

### ISSUE THREAD

**Issue by SiBell** [birminghamurbanobservatory/public-data-hub#4]
Currently all the map markers showing top level platforms are red. Could we use a different colour for different deployments?

**Comment by SiBell** [comment]
N.B. each platform has a `inDeployment` property. This is how we now what deployment the top level platform belongs to.

**Comment by SiBell** [comment]
There's a bug where two different deployments `netatmo-gatekeepers` and `public-netatmo` are exactly the same shade of brown.

**Comment by Gramcito** [comment]
Pushed a fix for this but colours are bit random. The only way we can improve this to have an array of colours and fall back to random colours if we need them.

**Comment by SiBell** [comment]
I'm happy enough with the random colours. I've changed the shape of platform markers to circles in commit https://github.com/birminghamurbanobservatory/public-data-hub/commit/32db9915395c80acee9c50d54eb0430ca7c3d198 which looks a bit cooler to me. As far as I can tell the alignment is ok, i.e. the middle of the circle on on the exact lat/lon, but I only checked this quickly.
