### ISSUE TITLE
Gardener friendly data visualisations

### ISSUE THREAD

**Issue by SiBell** [birminghamurbanobservatory/public-data-hub#43]
Possible additions that would be more user-friendly for gardeners:

- Temperature: ( current, max and min in last 24 hours and daily for last 7 days (air temp/ ground temperature)
- Precipitation: hourly bar chart for last 24 hours, daily bar chart for last 7 days; cumulative month to date, past months cumulative totals for 12 months.
- Wind speed and direction, max. Speed/gusts in last 24 hours; wind chill.
- Sunshine: hours of sunshine in last 24 hours, 7 days, cumulative total for month and last 12 months
- Pressure: current atmospheric pressure and indication of whether rising or falling I.e. a simple barometer

A decision will need to be made on how to calculate these statistics over long periods (hourly, daily). Options:

- Calculate on server side and save to database.
- Calculate on the fly on the server side in response to api request.
- Calculate on the fly in the browser. 

In all instances we need to be really careful about missing data. For example, many of the weather stations take a while to transmit data, so it would be risky to calculate a daily average at midnight because data between 23:00 and 00:00 may not have arrived yet.

**Comment by birminghamurbanobservatory** [comment]
Haven't been able to implement all of this as it's a little too bespoke for this generic web app, although we do calculate the total precip accumulation over the plotted time-frame which is a bit nicer than what we had before.
