### ISSUE TITLE
Change Platform hierarchy icons

### ISSUE THREAD

**Issue by SiBell** [birminghamurbanobservatory/public-data-hub#48]
I like the idea of having icons, we just need to see if there's something better than using open/closed folder icons.

**Comment by Gramcito** [comment]
I've replaced the folders with carets. Let me know what you think.

**Comment by SiBell** [comment]
Much better. Although the carets make me think that they will expand and collapse if I click them.

This any better:

```js
<li *ngFor="let platform of obs.ancestorPlatforms; index as i; first as isFirst" [ngClass]="[i > 0 ? 'ml-' + i*2 : '']">
    <span class="ml-1"><span *ngIf="!isFirst">⤷</span> {{ platform }}</span>
</li> 
``` 

<img width="290" alt="Screenshot 2020-06-30 at 12 33 15" src="https://user-images.githubusercontent.com/7696671/86121429-e0c09180-bacd-11ea-826c-e3d564705f3b.png">

Plenty of [other arrows](https://www.key-shortcut.com/en/writing-systems/35-symbols/arrows) to choose from. E.g. ↳. Hopefully they're widely supported.

**Comment by Gramcito** [comment]
Had the same thought about the carets. Implemented.
