### ISSUE TITLE
Check plots colours are correct

### ISSUE THREAD

**Issue by SiBell** [birminghamurbanobservatory/public-data-hub#52]
Not 100% that the colours on the plot page used for both the graph and the timeseries info align. E.g. what happens when timeseries drop in and out when new time frames are selected.

**Comment by SiBell** [comment]
Also the colours for the timeseries are lighter. Is there an opacity setting somewhere.

**Comment by SiBell** [comment]
These timeseries information cards want beautifying a bit too. E.g. do we need the header? Also make smaller. Also don't look right on small screen.

**Comment by SiBell** [comment]
Use a dot to show the colour, rather than colouring the whole header.

**Comment by Gramcito** [comment]
Added dot same colour as timeseries 'point' on chart, also left the header text same colour. Works well I think.
