### ISSUE TITLE
Make it clearer when no data available to plot

### ISSUE THREAD

**Issue by SiBell** [birminghamurbanobservatory/public-data-hub#56]
If the timeseries don't have an data over the selected period then tell the user this rather than showing an empty graph. Using the first and last obs properties of the timeseries we could suggest a timeframe when there is data with a button to plot it.

**Comment by SiBell** [comment]
This is particularly an issue for column charts.

**Comment by SiBell** [comment]
But also an issue for line charts.

**Comment by Gramcito** [comment]
Pushed up a solution that hides the chart if obsTally is zero and gettingObs is false and instead display a panel with 'error' text. 

Perhaps we can add the first observation date to each panel for each timeseries present and refer the user to that in the 'error' text, or is that query too costly on the api?

**Comment by SiBell** [comment]
Hi @Gramcito. Solution works well.

So the timeseries objects themselves each have start and end date properties. I.e. the date of the first and last observations of the timeseries. So we could just find the max end date and use this to create a link below the error message. E.g. "click here to see the most recent data available".

We do have this weird situation at the moment though, as demonstrated [here](http://localhost:4200/plot?ancestorPlatforms__includes=chilcote-primary-school&observedProperty=air-temperature&unit=degree-celsius) where you can end up with timeseries listed that aren't visible in the graph. The question is whether each of these should have a "plot most recent from this timeseries" link at the bottom of the card. Although I kinda feel like this might get ugly. Hmm....
