### ISSUE TITLE
Update the browser's URL more often

### ISSUE THREAD

**Issue by SiBell** [birminghamurbanobservatory/public-data-hub#6]
For example when the map is changed from a view of platforms to a view of air temperatures across Birmingham we should update the URL. 

This way we can post a link, e.g. on Twitter, that takes a user directly to the map of air temperatures rather than forcing them to navigate there themselves.

**Comment by SiBell** [comment]
Could even argue it's worth including the observation ID in the URL when the observation modal is loaded.

**Comment by Gramcito** [comment]
Had little play with this, and whilst easy enough to do, the playing made me realise that we need to have a think and chat about our url structure and what 'pages' we need. 

Something like: whatever.com/map/<observedProperty>, because we potentially already have: whatever.com/<platform>/<observedProperty>.

**Comment by SiBell** [comment]
Yer might have to be that when a user goes to the root `/` it defaults to `/map` which shows the platforms to begin with, then when they click the air temperature icon the URL becomes:

`/map?observedProperty=AirTemperature`

Couple of other things that have sprung to mind:

- When we're showing observations rather than platforms then the deployment legend we plan to add for platforms should be replaced with a date/time picker so they can see air temperature observations at a particular time in the past. In which case the URL should change again:

`/map?observedProperty=AirTemperature&resultTime=2020-04-16T12:00:00.000Z`

- This has also got me thinking about lazy loading modules, which is probably worth doing if we haven't already. E.g. no need to load all the timeseries line graph code straight away.

**Comment by SiBell** [comment]
[Here's](https://github.com/birminghamurbanobservatory/admin-web-app/blob/master/src/app/app-routing.module.ts) an example of lazy loading implemented in my admin application, and [here's](https://github.com/birminghamurbanobservatory/admin-web-app/blob/master/src/app/sensor/sensors/sensors.component.ts) how I read and update query parameters.

**Comment by Gramcito** [comment]
I implemented lazy loading at the start. :-)

**Comment by SiBell** [comment]
👌

**Comment by Gramcito** [comment]
Went with child routes rather than having to check the query param which looked like it might get messy quickly... and all those 'if' statements made my OCD itch! :-D

**Comment by Gramcito** [comment]
Check the end of the walkthrough document, put a suggested site map in there.

**Comment by SiBell** [comment]
I've updated the walkthrough with the URLs I'd like in commit 61df2802f89c9d5b035499076973ac535fef6c03.
