### ISSUE TITLE
Prettify plot loading

### ISSUE THREAD

**Issue by SiBell** [birminghamurbanobservatory/public-data-hub#60]
We currently have a simple line of text that shows how many observations have been loaded thus far. Is there a nicer way of doing this? 

E.g. have a modal, or screen overlay, that shows the current observations count, along with a spinner, and has a cancel button for when the user realises they've made a terrible mistake asking for a year's worth of data.

**Comment by Gramcito** [comment]
Added in a model that allows the user to cancel the observation retrieval and provides feedback when they do so.
