### ISSUE TITLE
Modal still a bit too large

### ISSUE THREAD

**Issue by SiBell** [birminghamurbanobservatory/public-data-hub#65]
The modal isn't always showing everything without a vertical scroll. I've remove a fair bit of content, but apparently not enough.

Might want to look at reducing the margins/padding a little.

Also the aggregation type doesn't need its own line. We should try to duplicate the approach used in the platform sidebar, i.e. the grey text below the observation, e.g. "instant reading".

**Comment by SiBell** [comment]
Still want to show the start and end of the aggregation period (for obs that aren't _instant_), and the duration string is quite useful too (e.g. 5 minute avg). However these 3 bits of information take up a lot of space. 

Could move `5 minute avg` underneath the observation value itself, and the start and end times could be show on the same line?

**Comment by Gramcito** [comment]
http://localhost:4200/map/observations?observedProperty=precipitation-rate&disciplines__includes=meteorology&unit=millimetre-per-hour&aggregation__in=instant,average&duration__lt=3630

**Comment by Gramcito** [comment]
Implemented as described above.
