### ISSUE TITLE
Modal sometimes too wide for screen (on mobile)

### ISSUE THREAD

**Issue by SiBell** [birminghamurbanobservatory/public-data-hub#67]
End up with left to right movement on the page.

<img width="404" alt="Screenshot 2020-06-26 at 18 51 51" src="https://user-images.githubusercontent.com/7696671/85886592-47982f00-b7de-11ea-9ab0-7138a2280d82.png">

**Comment by Gramcito** [comment]
Struggling to replicate this one, same sensor and site but not happening on any mobile screen.

**Comment by SiBell** [comment]
Yer me neither now. I'll close this for now and hope we don't see it again.
