### ISSUE TITLE
Plot back button bug

### ISSUE THREAD

**Issue by SiBell** [birminghamurbanobservatory/public-data-hub#76]
@Gramcito, love the idea of the back button (pic below), however if you change the time frame on the plot then the back button just goes back to the previous time frame rather than back to map.

<img width="522" alt="Screenshot 2020-06-30 at 19 09 50" src="https://user-images.githubusercontent.com/7696671/86161521-48460380-bb05-11ea-81ba-ab5e4d2d07b9.png">

**Comment by Gramcito** [comment]
Damn it!
