### ISSUE TITLE
Bug with plot loading modal

### ISSUE THREAD

**Issue by SiBell** [birminghamurbanobservatory/public-data-hub#80]
Great work on this modal. Very funny.

I think the state of the cancel button needs refreshing though. E.g. if you run a bit request and click cancel, then let it plot what it has, then select another big timeframe the modal appears with "cancelling" still written in the button.

**Comment by Gramcito** [comment]
Ah, bet I missed that when I moved it to its own component. Easy enough to fix as just need to link the reset. 

Glad you appreciated the humour! :-)
