### ISSUE TITLE
Platform sidebar height on mobile

### ISSUE THREAD

**Issue by SiBell** [birminghamurbanobservatory/public-data-hub#85]
The sidebar on the map page with the platform details/observations ends up being longer than the map on mobile screen sizes. It therefore ends up covering the list of Deployments below the map.

It works as we'd want it too on large screen sizes though.

**Comment by Gramcito** [comment]
I kind of feel this working how it should. On mobile it works more like a modal as there simply is not the screen space to work like it does on desktop.

If restricted to the height of the map you would be trying to scroll with touch on a scrollable screen.

**Comment by SiBell** [comment]
I see what you're saying. The solution could well be worse.
