### ISSUE TITLE
Update URL when a deployment is selected on map?

### ISSUE THREAD

**Issue by SiBell** [birminghamurbanobservatory/public-data-hub#88]
E.g. when Automatic Urban and Rural Network is selected from the Deployments Legend, the url changes to `/map/platforms?deployment=aurn`

This would make it easier to share links to a specific deployment.

Hopefully we can update the URL without having the map completely refresh.

**Comment by Gramcito** [comment]
Decision made and implemented. No reload of the map required as just taps in to existing functionality.
