### ISSUE TITLE
Overlapping markers, e.g. for air temperature

### ISSUE THREAD

**Issue by SiBell** [birminghamurbanobservatory/public-data-hub#9]
On the map of air temperature you can get some locations where the map markers are on top of each other, e.g. because a platform has more than one sensor capable of measuring air temperature. Because the markers are slightly transparent you end up with the number behind showing through.

Couple of options here:

- Make each marker opaque.
- Use [Marker Clustering](https://developers.google.com/maps/documentation/javascript/marker-clustering).

I'd veer towards the top option as I can't stand maps with marker clustering. The question is do we need the user to be aware that the top marker is hiding more markers below it. Probably, but I can't think of an easy way of doing this.

**Comment by Gramcito** [comment]
I think the answer to your question is, use marker clustering! Anything else would be difficult and is exactly what clustering was designed for! :-D

**Comment by SiBell** [comment]
So my worry is that upon loading the map page the user is presented with a load of cluster icons and very little useful information. Also even if the user zooms in so that the cluster icon goes, they'll still only see one temperature icon. 

If in doubt check out [stackoverflow](https://stackoverflow.com/questions/3548920/google-maps-api-v3-multiple-markers-on-exact-same-spot). A [Spiderfier](https://github.com/jawj/OverlappingMarkerSpiderfier) might be what we want? Check out the [demo](https://jawj.github.io/OverlappingMarkerSpiderfier/demo-1.html).

**Comment by Gramcito** [comment]
Ah, yes. Because your readings will have exactly the same coords rather than simply being close. Seen the spidery thing used before will have a look into it.

**Comment by Gramcito** [comment]
Justing making a note of this here: https://www.npmjs.com/package/ts-overlapping-marker-spiderfier

**Comment by SiBell** [comment]
We discussed potentially going back to a native google map for the sake of the spiderfier. 

Here's an approach I'm currently using for loading Google Maps and making sure it's ready:

https://github.com/birminghamurbanobservatory/admin-web-app/blob/master/src/app/location/google-maps/google-maps-loader.ts

And here's an example of a component using this _loader_:

https://github.com/birminghamurbanobservatory/admin-web-app/blob/master/src/app/location/location-viewer/location-viewer.component.ts

It could possibly do with being updated to use Observables rather than a Promise.

**Comment by SiBell** [comment]
And with respect to how the spiderfier should work:

- Set the opacity of all markers to 100% so we can't see those directly behind.
- When a user clicks on a marker there should hopefully be an event emitter that tells us whether this marker has triggered a spider or not. If not show the modal/sidebar as usual, if it has then wait until the user clicks on one of the spidered markers before loading modal/sidebar.
- For now at least I'd simply keep the marker icons the same as there are now, rather than trying to  make them square or dashed if they're a marker that has others behind it.

**Comment by Gramcito** [comment]
Setting the fill opacity to 100% did not stop the text overlap.

The spiderfier is working on the Observed Property map but needs a couple of small tweaks, e.g. spidered icons close when one clicked.

**Comment by Gramcito** [comment]
I think comment 95861a0 fixes every thing. Ended up adding '+' for icons that can be expanded, made it more intuitive but can delete easily if you prefer. Just let me know.

**Comment by SiBell** [comment]
Hi Graham. I think this concept works really well. Let's see how we get on with the "+", could work nicely given that we still have the colour behind it.

There's a couple of minor bugs I've spotted:

1. If you spidify one of the "+" markers, then click on another "+" marker elsewhere on the map the modal opens rather than spidifying the second marker.
2. If you zoom right out each marker turns to a "+" and then doesn't recover when you zoom back in.

**Comment by Gramcito** [comment]
Okay, I've noticed one too: no '+' when you change from platform map to observed property map but is there when load directly in to an observed property map (which of course I was doing in dev).

**Comment by Gramcito** [comment]
Okay, fixed two of three. I am not experience the modal issue when clicking on a second "+", and as cannot replicate... cannot fix. Browser issue? I am using Chrome. 

For the bug I noted I had to add a work-around as could not figure out what was causing the difference at all.

**Comment by SiBell** [comment]
The bugs I spotted are all gone now. Great work.

The only minor thing that's bugging me is when we get a situation like this:

<img width="290" alt="Screenshot 2020-06-02 at 14 29 19" src="https://user-images.githubusercontent.com/7696671/83526064-c8b11e80-a4dd-11ea-8a75-3c68842fbf1e.png">

In particular the two bottom left `+`'s. To me they're not overlapping enough to warrant spiderfying. I'm guessing there's no parameter that lets us config the overlap threshold? If not feel free to close this issue because all the workarounds I can think of (e.g. showing the temperature value rather than a "+") will have side-effects that are even more confusing to the end user.

**Comment by Gramcito** [comment]
There is in fact a setting, 'nearbyDistance' when you new up the spiderfy map instance. Defaults to 20px, we just need to play around with that value - although seems not to be such an issue for me. 
<img width="307" alt="Screenshot 2020-06-03 at 09 05 10" src="https://user-images.githubusercontent.com/7080217/83611858-79203080-a579-11ea-99cd-7465b7b1b5a2.png">
