### ISSUE TITLE
Modify default plot time windows?

### ISSUE THREAD

**Issue by SiBell** [birminghamurbanobservatory/public-data-hub#92]
I.e. instead of last 6 hours, 12 hours and 24 hours how about:

- last 6 hours
- last 24 hours
- last 7 days

**Comment by Gramcito** [comment]
Last seven days would result in a lot of observations to plot for some time series but otherwise easy enough to implement - though you did change the default set up.

**Comment by SiBell** [comment]
True. Perhaps 3, rather than 7, days is more sensible.

**Comment by Gramcito** [comment]
I tagged you for this... :-D 

I abdicate all responsibility.

**Comment by SiBell** [comment]
Haha, yer fair enough. I'll have a play.

**Comment by SiBell** [comment]
implemented
