### ISSUE TITLE
Delete Pages/PlatformDetail

### ISSUE THREAD

**Issue by SiBell** [birminghamurbanobservatory/public-data-hub#99]
Is the folder _Pages/PlatformDetail_ now obsolete? Can it be deleted.

Looks like _Pages/Map/platform-detail_ is the directory actually being used.

**Comment by Gramcito** [comment]
Yeah, think it was for when we might do a platform listing... and pretty sure it is not being used anyway.

**Comment by SiBell** [comment]
Brill. I'll remove that bit then.

**Comment by SiBell** [comment]
deleted as part of massive restructure
